name: Report a bug
description: Something is not working? Report a bug
body:

  - type: textarea
    id: context
    attributes:
      label: Context
      description: >-
        This field is optional. You may provide additional context for the bug
        you want to report, helping us to understand what you are working on and
        what you are trying to achieve. If the context is not relevant, you can
        leave this field empty.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#context)

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: >-
        Please give a detailed description of the bug. Explain where CoRA
        does not behave as you would expect it to. Be as specific as
        possible. If you have found a workaround or a fix for the problem,
        please let us maintainers (and all other users) know.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#bug-description)
    validations:
      required: true

  - type: textarea
    id: related-links
    attributes:
      label: Related links
      description: >-
        Please list all links to the sections of
        [our documentation](https://docs/coracore.org/) that
        are relevant to the bug in order to show that you have consulted and
        thoroughly read it. Additionally, list links to possibly related open
        and closed [issues](https://github.com/spawaskar-cora/cora-docs/issues)
        and [discussions](https://github.com/spawaskar-cora/cora-docs/discussions)
        you encountered when searching our issue tracker.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#related-links)
      value: |-
        - [Reporting a bug](https://docs/coracore.org/contributing/reporting-a-bug/)
        -
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        Please provide a detailed list of instructions, guiding us maintainers
        through the required steps, helping us to recreate the problem. Be as specific 
        as possible and as verbose as necessary – try not to leave anything out.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#steps-to-reproduce)
      placeholder: |-
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: >-
        This field is optional. If the bug only happens in __specific device__,
        please select them from the dropdown below. If your device is not
        listed or the version is relevant, you may select _Other_ and provide
        more details in the field above.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#browser)
      multiple: true
      options:
        - Desktop
        - Tablet
        - Smart Phone
        - Other

  - type: dropdown
    id: os
    attributes:
      label: OS
      description: >-
        This field is optional. If the bug only happens on __specific operating systems__,
        please select them from the dropdown below. If your OS is not
        listed or the version is relevant, you may select _Other_ and provide
        more details in the field above.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#browser)
      multiple: true
      options:
        - Windows
        - Mac
        - iOS
        - Android
        - Other

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: >-
        This field is optional. If the bug only happens in __specific browsers__,
        please select them from the dropdown below. If your browser is not
        listed or the version is relevant, you may select _Other_ and provide
        more details in the field above.
        [More](https://docs/coracore.org/contributing/reporting-a-bug/#browser)
      multiple: true
      options:
        - Chrome
        - Safari
        - Edge
        - Firefox
        - Opera
        - Other

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      description: >-
        Please ensure your bug report fulfills all of the following requirements.
        If you are not sure what a specific requirement means, follow the link
        to learn about it and understand why it is necessary before ticking the
        box. This will save the maintainers and you valuable time.
      options:
        - label: >-
            I have read and followed the [bug reporting guidelines](https://docs/coracore.org/contributing/reporting-a-bug/).
          required: true
        - label: >-
            I have attached links to [the documentation](https://docs/coracore.org/),
            and possibly related [issues](https://github.com/spawaskar-cora/cora-docs/issues)
            and [discussions](https://github.com/spawaskar-cora/cora-docs/discussions).
          required: true
        - label: >-
            I assure that I have [removed all customizations](https://docs/coracore.org/contributing/reporting-a-bug/#remove-customizations)
            before submitting this bug report.
          required: true
